travis:
  secure:
    BINSTAR_TOKEN: hPjnhG7ZmJ1Jw3Kdb5jxtf0Lpkmv1LuF5ohbgnQCEFkuSDl8RPes/LHVvS6F7CHSrgzZMNMbM/A4vexlIXuwKDIZxW+AgZ2VvRQ4Fw2/RkMm4Nm39soUn51wENqotIP4sGZj868wUuGDxg0OCFTWIe07qv2c+zIMboGufuna2diuHVuUb8T2j6fUnlW3BMFmFMLQgMP2CZIcANKxlLoe0nWwnV+SOnh0SWxMI5Pnei9hue5MlMRTt3sfVWwQbArQtTaU7sliMmc3cszCFab1lEabYgwmdr0/JdHpgRbRm1bw6yOz1vDsf4H5mDGwaO398Wav7pgaAT/wAk15MziurDzUnN1SHpNb9KqKSo3wCEIA4jdmBkXBUCbiDBJaNg6RX344/Agc3VSbJyzp9pgZtVAOkPQmbLEXzqpJ+NT+O/ZMwwZ8TA4YsfC1sVU36UZpATfd3D6ye+5HA68osoMihvo4IKDCijPoLV/roxeLLYA77E0wNLUDh+1XgWtIuWOuQKsx1X+zRE8OFUCxYl8qXArfLfFgbuN/02MLOf+4rDgHmskToIKIHcjeNYZdqyQkOWoVjvocgnb1QUsxpXZUNrQR5YWh0hsqSKAr5TyrsRrk/P4k+WncGHNPBw9SilATQXAtu/hqTdrhJO5Y8Xc/oZxjYJC8z/hKODU/N3X3t3E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
